name: generate

on:
  push:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: [5]
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/base_${{ matrix.base-diameter }}_nodemcu_v2.stl -D board=${{ matrix.board }} -D base_diameter=${{ matrix.base-diameter }} base.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  display:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        display: [1, 2]
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/module_${{ matrix.base-diameter }}_oled${{ matrix.display }}.stl -D display=${{ matrix.display }} -D base_diameter=${{ matrix.base-diameter }} module_oled.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  pir:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/module_${{ matrix.base-diameter }}_pir.stl -D base_diameter=${{ matrix.base-diameter }} module_pir.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  dome:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/cap_${{ matrix.base-diameter }}_dome.stl -D base_diameter=${{ matrix.base-diameter }} cap_dome.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  empty:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/module_${{ matrix.base-diameter }}_empty.stl -D base_diameter=${{ matrix.base-diameter }} module_empty.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  enclosure:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        base-diameter: [62.8, 67, 80]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install OpenSCAD
        run: |
          wget -qO - https://files.openscad.org/OBS-Repository-Key.pub | sudo apt-key add -
          echo 'deb http://download.opensuse.org/repositories/home:/t-paul/xUbuntu_20.04/ ./' | sudo tee --append /etc/apt/sources.list.d/openscad.list
          sudo apt-get update -qq
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y openscad-nightly
          sudo ln -s /usr/bin/openscad-nightly /usr/bin/openscad
          sudo pip install svg.path==2.2

      - name: Create build dir
        run: mkdir build

      - name: Generate STLs
        run: |
          openscad -o build/module_${{ matrix.base-diameter }}_enclosure.stl -D base_diameter=${{ matrix.base-diameter }} module_enclosure.scad

      - name: Store STL artifacts
        uses: actions/upload-artifact@v2
        with:
          name: stl
          path: build
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    needs: [base, display, pir, dome, empty, enclosure]
    steps:
      - name: Download STL artifacts
        uses: actions/download-artifact@v2
        with:
          name: stl
          path: build

      - name: Publish STLs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
